package co.unicauca.workflow.degree_project.presentation;

import co.unicauca.workflow.degree_project.domain.services.IRegistrationService;
import co.unicauca.workflow.degree_project.presentation.modules.NuevoTGPanel;
import co.unicauca.workflow.degree_project.presentation.modules.MiTrabajoPanel;
import co.unicauca.workflow.degree_project.presentation.modules.PrincipalEstudiantePanel;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import co.unicauca.workflow.degree_project.domain.services.ISignInService;

public class GUIEstudiante extends javax.swing.JFrame {
    private final IRegistrationService registration;
    private final ISignInService authService;

    /**
     * Creates new form GUIEstudiante
     */
    public GUIEstudiante(ISignInService authService, IRegistrationService registration) {
        this.authService = authService;
        this.registration = registration;
        initComponents();
        initContent();
    }
      
    private void initContent(){
        setLocationRelativeTo(null);
        ShowJPanel(new PrincipalEstudiantePanel());
    }
    
    private void ShowJPanel(JPanel p){
        p.setSize(722, 440);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        linea = new javax.swing.JPanel();
        TitleMenu = new javax.swing.JLabel();
        BtnMiTrabajoDeGrado = new javax.swing.JButton();
        BtnIniciarNuevoTrabajoDeGrado = new javax.swing.JButton();
        BtnPrincipal = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        EMensaje = new java.awt.Label();
        TitleUnicauca = new java.awt.Label();
        LogoUnicauca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1020, 640));

        menu.setBackground(new java.awt.Color(32, 44, 103));
        menu.setPreferredSize(new java.awt.Dimension(270, 500));

        linea.setBackground(new java.awt.Color(255, 255, 255));
        linea.setPreferredSize(new java.awt.Dimension(154, 2));

        javax.swing.GroupLayout lineaLayout = new javax.swing.GroupLayout(linea);
        linea.setLayout(lineaLayout);
        lineaLayout.setHorizontalGroup(
            lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        lineaLayout.setVerticalGroup(
            lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        TitleMenu.setBackground(new java.awt.Color(255, 255, 255));
        TitleMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleMenu.setForeground(new java.awt.Color(255, 255, 255));
        TitleMenu.setText("Menu");

        BtnMiTrabajoDeGrado.setBackground(new java.awt.Color(32, 44, 103));
        BtnMiTrabajoDeGrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnMiTrabajoDeGrado.setForeground(new java.awt.Color(255, 255, 255));
        BtnMiTrabajoDeGrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libro.png"))); // NOI18N
        BtnMiTrabajoDeGrado.setText("Mi trabajo de grado");
        BtnMiTrabajoDeGrado.setBorder(null);
        BtnMiTrabajoDeGrado.setBorderPainted(false);
        BtnMiTrabajoDeGrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMiTrabajoDeGrado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnMiTrabajoDeGrado.setVerifyInputWhenFocusTarget(false);
        BtnMiTrabajoDeGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMiTrabajoDeGradoActionPerformed(evt);
            }
        });

        BtnIniciarNuevoTrabajoDeGrado.setBackground(new java.awt.Color(32, 44, 103));
        BtnIniciarNuevoTrabajoDeGrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnIniciarNuevoTrabajoDeGrado.setForeground(new java.awt.Color(255, 255, 255));
        BtnIniciarNuevoTrabajoDeGrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hoja.png"))); // NOI18N
        BtnIniciarNuevoTrabajoDeGrado.setText("<html>Iniciar nuevo Trabajo de Grado</html>");
        BtnIniciarNuevoTrabajoDeGrado.setActionCommand("<html>Iniciar nuevo Trabajo de Grado</html>");
        BtnIniciarNuevoTrabajoDeGrado.setBorder(null);
        BtnIniciarNuevoTrabajoDeGrado.setBorderPainted(false);
        BtnIniciarNuevoTrabajoDeGrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIniciarNuevoTrabajoDeGrado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnIniciarNuevoTrabajoDeGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarNuevoTrabajoDeGradoActionPerformed(evt);
            }
        });

        BtnPrincipal.setBackground(new java.awt.Color(32, 44, 103));
        BtnPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casa.png"))); // NOI18N
        BtnPrincipal.setText("  Principal");
        BtnPrincipal.setBorder(null);
        BtnPrincipal.setBorderPainted(false);
        BtnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrincipalActionPerformed(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(32, 44, 103));
        BtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salirG.png"))); // NOI18N
        BtnSalir.setText("  Salir");
        BtnSalir.setBorder(null);
        BtnSalir.setBorderPainted(false);
        BtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnMiTrabajoDeGrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnIniciarNuevoTrabajoDeGrado, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(TitleMenu)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(BtnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(TitleMenu)
                .addGap(18, 18, 18)
                .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BtnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnMiTrabajoDeGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnIniciarNuevoTrabajoDeGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMinimumSize(new java.awt.Dimension(722, 440));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        header.setBackground(new java.awt.Color(87, 132, 192));
        header.setPreferredSize(new java.awt.Dimension(610, 98));

        EMensaje.setAlignment(java.awt.Label.CENTER);
        EMensaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EMensaje.setForeground(new java.awt.Color(0, 0, 102));
        EMensaje.setText("acompañando el avance hacia la excelencia académica");

        TitleUnicauca.setAlignment(java.awt.Label.CENTER);
        TitleUnicauca.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TitleUnicauca.setForeground(new java.awt.Color(255, 255, 255));
        TitleUnicauca.setText("Universidad del Cauca");

        LogoUnicauca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escudo Unicauca Pequeño.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(TitleUnicauca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(151, 151, 151))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(EMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(LogoUnicauca)
                .addGap(15, 15, 15))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoUnicauca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(TitleUnicauca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(EMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        EMensaje.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrincipalActionPerformed
        ShowJPanel(new PrincipalEstudiantePanel());
    }//GEN-LAST:event_BtnPrincipalActionPerformed

    private void BtnMiTrabajoDeGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMiTrabajoDeGradoActionPerformed
        ShowJPanel(new MiTrabajoPanel());
    }//GEN-LAST:event_BtnMiTrabajoDeGradoActionPerformed

    private void BtnIniciarNuevoTrabajoDeGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarNuevoTrabajoDeGradoActionPerformed
        ShowJPanel(new NuevoTGPanel());
    }//GEN-LAST:event_BtnIniciarNuevoTrabajoDeGradoActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        GUISignIn iniciar = new GUISignIn(authService, registration);
        iniciar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GUIEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciarNuevoTrabajoDeGrado;
    private javax.swing.JButton BtnMiTrabajoDeGrado;
    private javax.swing.JButton BtnPrincipal;
    private javax.swing.JButton BtnSalir;
    private java.awt.Label EMensaje;
    private javax.swing.JLabel LogoUnicauca;
    private javax.swing.JLabel TitleMenu;
    private java.awt.Label TitleUnicauca;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JPanel linea;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
