/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.workflow.degree_project.presentation;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Laura
 */
public class GUISignUp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUISignUp.class.getName());

    /**
     * Creates new form GUIPrueba
     */
    public GUISignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
        SwingUtilities.invokeLater(() -> {
            Escudo.requestFocusInWindow();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBackGround = new javax.swing.JPanel();
        Escudo = new javax.swing.JLabel();
        lblNoCuenta = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        sepUsuario = new javax.swing.JSeparator();
        lblConrtaseña = new javax.swing.JLabel();
        txtConrtaseña = new javax.swing.JPasswordField();
        sepContraseña = new javax.swing.JSeparator();
        BotonRegistrarse = new javax.swing.JPanel();
        lblBotonRegistrarse = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblRegistrarse = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        sepUsuario1 = new javax.swing.JSeparator();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        sepUsuario2 = new javax.swing.JSeparator();
        lblPrograma = new javax.swing.JLabel();
        cbxPrograma = new javax.swing.JComboBox<>();
        lblRol = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();
        lblCondiciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jBackGround.setPreferredSize(new java.awt.Dimension(800, 500));
        jBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Escudo.setFont(new java.awt.Font("Roboto SemiCondensed", 1, 14)); // NOI18N
        Escudo.setForeground(new java.awt.Color(0, 51, 204));
        Escudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Escudo Unicauca Pequeño.png"))); // NOI18N
        Escudo.setToolTipText("");
        jBackGround.add(Escudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 60, 90));

        lblNoCuenta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblNoCuenta.setText("¿Ya tienes una cuenta?");
        jBackGround.add(lblNoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo.setText("Ingrese su correo institucional");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        jBackGround.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 290, 20));

        sepUsuario.setBackground(new java.awt.Color(255, 255, 255));
        sepUsuario.setForeground(new java.awt.Color(0, 102, 204));
        sepUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sepUsuario.setPreferredSize(new java.awt.Dimension(270, 10));
        jBackGround.add(sepUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        lblConrtaseña.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblConrtaseña.setText("CONTRASEÑA");
        jBackGround.add(lblConrtaseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 130, -1));

        txtConrtaseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtConrtaseña.setForeground(new java.awt.Color(102, 102, 102));
        txtConrtaseña.setText("**********");
        txtConrtaseña.setBorder(null);
        txtConrtaseña.setPreferredSize(new java.awt.Dimension(270, 20));
        txtConrtaseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtConrtaseñaMousePressed(evt);
            }
        });
        jBackGround.add(txtConrtaseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 270, 20));

        sepContraseña.setBackground(new java.awt.Color(255, 255, 255));
        sepContraseña.setForeground(new java.awt.Color(0, 102, 204));
        sepContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sepContraseña.setPreferredSize(new java.awt.Dimension(270, 10));
        jBackGround.add(sepContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        BotonRegistrarse.setBackground(new java.awt.Color(0, 102, 204));

        lblBotonRegistrarse.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblBotonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        lblBotonRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBotonRegistrarse.setText("Registrarse");
        lblBotonRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonRegistrarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BotonRegistrarseLayout = new javax.swing.GroupLayout(BotonRegistrarse);
        BotonRegistrarse.setLayout(BotonRegistrarseLayout);
        BotonRegistrarseLayout.setHorizontalGroup(
            BotonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBotonRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        BotonRegistrarseLayout.setVerticalGroup(
            BotonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonRegistrarseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBotonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBackGround.add(BotonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 120, 40));

        lblUsuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblUsuario.setText("USUARIO");
        jBackGround.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 80, -1));

        lblRegistrarse.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblRegistrarse.setText("Inicia sesión");
        lblRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseExited(evt);
            }
        });
        jBackGround.add(lblRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paisaje recortado.jpg"))); // NOI18N
        jBackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        lblNombres.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblNombres.setText("NOMBRES");
        jBackGround.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 90, -1));

        txtNombres.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(102, 102, 102));
        txtNombres.setText("Ingrese su/s nombre/s");
        txtNombres.setBorder(null);
        txtNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombresMousePressed(evt);
            }
        });
        jBackGround.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 290, 20));

        sepUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        sepUsuario1.setForeground(new java.awt.Color(0, 102, 204));
        sepUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sepUsuario1.setPreferredSize(new java.awt.Dimension(270, 10));
        jBackGround.add(sepUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        lblApellidos.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblApellidos.setText("APELLIDOS");
        jBackGround.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, -1));

        txtApellidos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidos.setText("Ingrese sus apellidos");
        txtApellidos.setBorder(null);
        txtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidosMousePressed(evt);
            }
        });
        jBackGround.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 290, 20));

        sepUsuario2.setBackground(new java.awt.Color(255, 255, 255));
        sepUsuario2.setForeground(new java.awt.Color(0, 102, 204));
        sepUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sepUsuario2.setPreferredSize(new java.awt.Dimension(270, 10));
        jBackGround.add(sepUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        lblPrograma.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblPrograma.setText("SELECCIONE SU PROGRAMA");
        jBackGround.add(lblPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        cbxPrograma.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbxPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería de Sistemas", "Ingeniería Electrónica", "Telecomunicaciones", "Automática industrial", "Tecnología en Telemática" }));
        jBackGround.add(cbxPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 270, -1));

        lblRol.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblRol.setText("SELECCIONE SU ROL");
        jBackGround.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        cbxRol.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente" }));
        jBackGround.add(cbxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 270, -1));

        lblCondiciones.setForeground(new java.awt.Color(0, 51, 102));
        lblCondiciones.setText("<html><div style='width:200px;'>* La contraseña debe tener mínimo 6 caracteres, al menos un dígito, al menos un carácter especial y al menos una mayúscula </div></html>\n");
        lblCondiciones.setToolTipText("");
        jBackGround.add(lblCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseEntered
        lblRegistrarse.setForeground(Color.BLUE);
        lblRegistrarse.setFont(new Font("Roboto", Font.BOLD, 12));
    }//GEN-LAST:event_lblRegistrarseMouseEntered

    private void lblRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseExited
        lblRegistrarse.setForeground(Color.BLACK);
        lblRegistrarse.setFont(new Font("Roboto", Font.PLAIN, 12));
    }//GEN-LAST:event_lblRegistrarseMouseExited

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        if(txtCorreo.getText().equals("Ingrese su correo institucional")){
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
        if(String.valueOf(txtConrtaseña.getPassword()).isEmpty()){
            txtConrtaseña.setText("**********");
            txtConrtaseña.setForeground(Color.gray);
        }
        if(txtNombres.getText().isEmpty()){
            txtNombres.setText("Ingrese su/s nombre/s");
            txtNombres.setForeground(Color.gray);
        }
        if(txtApellidos.getText().isEmpty()){
            txtApellidos.setText("Ingrese sus apellidos");
            txtApellidos.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtConrtaseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConrtaseñaMousePressed
        if(String.valueOf(txtConrtaseña.getPassword()).equals("**********")){
            txtConrtaseña.setText("");
            txtConrtaseña.setForeground(Color.black);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo institucional");
            txtCorreo.setForeground(Color.gray);
        }
        if(txtNombres.getText().isEmpty()){
            txtNombres.setText("Ingrese su/s nombre/s");
            txtNombres.setForeground(Color.gray);
        }
        if(txtApellidos.getText().isEmpty()){
            txtApellidos.setText("Ingrese sus apellidos");
            txtApellidos.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtConrtaseñaMousePressed
    
    // Método para validar JTextField
    private boolean esCampoInvalido(JTextField campo, String placeholder) {
        return campo.getText().trim().isEmpty() || campo.getText().equals(placeholder);
    }

    // Método para validar JPasswordField
    private boolean esCampoInvalido(JPasswordField campo, String placeholder) {
        String texto = String.valueOf(campo.getPassword());
        return texto.trim().isEmpty() || texto.equals(placeholder);
    }

    
    private void lblBotonRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonRegistrarseMouseClicked
        if (esCampoInvalido(txtCorreo, "Ingrese su correo institucional") ||
            esCampoInvalido(txtConrtaseña, "**********") ||
            esCampoInvalido(txtNombres, "Ingrese su/s nombre/s") ||
            esCampoInvalido(txtApellidos, "Ingrese sus apellidos")){
            JOptionPane.showMessageDialog(
                null,
                "Por favor, rellene todos los campos.",
                "Campos incompletos",
                JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_lblBotonRegistrarseMouseClicked

    private void txtNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresMousePressed
        if(txtNombres.getText().equals("Ingrese su/s nombre/s")){
            txtNombres.setText("");
            txtNombres.setForeground(Color.black);
        }
        if(String.valueOf(txtConrtaseña.getPassword()).isEmpty()){
            txtConrtaseña.setText("**********");
            txtConrtaseña.setForeground(Color.gray);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo institucional");
            txtCorreo.setForeground(Color.gray);
        }
        if(txtApellidos.getText().isEmpty()){
            txtApellidos.setText("Ingrese sus apellidos");
            txtApellidos.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombresMousePressed

    private void txtApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosMousePressed
        if(txtApellidos.getText().equals("Ingrese sus apellidos")){
            txtApellidos.setText("");
            txtApellidos.setForeground(Color.black);
        }
        if(String.valueOf(txtConrtaseña.getPassword()).isEmpty()){
            txtConrtaseña.setText("**********");
            txtConrtaseña.setForeground(Color.gray);
        }
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo institucional");
            txtCorreo.setForeground(Color.gray);
        }
        if(txtNombres.getText().isEmpty()){
            txtNombres.setText("Ingrese su/s nombre/s");
            txtNombres.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtApellidosMousePressed

    private void lblRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseClicked
        GUISignIn iniciar = new GUISignIn();
        iniciar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblRegistrarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUISignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonRegistrarse;
    private javax.swing.JLabel Escudo;
    private javax.swing.JComboBox<String> cbxPrograma;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JPanel jBackGround;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblBotonRegistrarse;
    private javax.swing.JLabel lblCondiciones;
    private javax.swing.JLabel lblConrtaseña;
    private javax.swing.JLabel lblNoCuenta;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPrograma;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JSeparator sepContraseña;
    private javax.swing.JSeparator sepUsuario;
    private javax.swing.JSeparator sepUsuario1;
    private javax.swing.JSeparator sepUsuario2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtConrtaseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
